name = "PubChemReactions"
uuid = "84d26278-d58d-42be-a39e-bf9de7ef3f0e"
authors = ["Utkarsh <rajpututkarsh530@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cascadia = "54eefc05-d75b-58de-a785-1a3403f0919f"
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Gumbo = "708ec375-b3d6-5a57-a7ce-8257bf98657a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PeriodicTable = "7b2266bf-644c-5ea3-82d8-af4bbd25a884"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1.8"
CSV = "0.10"
Cascadia = "1"
Catalyst = "12, 13, 14, 15"
DataFrames = "1.3"
DiffEqCallbacks = "2"
FileIO = "1.13"
Graphs = "1.6"
Gumbo = "0.8"
HTTP = "1"
ImageIO = "0.6"
InvertedIndices = "1"
JSON3 = "1.9"
OrdinaryDiffEq = "6"
PeriodicTable = "1"
Plots = "1.29"
StatsBase = "0.33"
Symbolics = "4, 5, 6"
URIs = "1"
Unitful = "1.9"

[extras]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["OrdinaryDiffEq", "Test"]
